### ISSUE TITLE
nixlinuxos インストール

### ISSUE THREAD

**Issue by machi-nao** [omemoji/dotfiles#2]
nixlinuxをライブusbから外付けusbをドライブにしてインストールしようとしたがインストーラーがパーテイションの作成ができずにインストールできませんでした、自動設定のパーテイションを設定したのではだめですか？

**Comment by omemoji** [comment]
恐らくこのリポジトリとは関係ない質問かと思われます（dotfilesは一連の設定ファイルであり、OSのインストールとは関係ありません）。
